{% set version = '0.5.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rerddap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rerddap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rerddap/rerddap_{{ version }}.tar.gz
  sha256: 8fb650ca315e002af7610c8608e10896d34b95260d197275be9aa4b3399328ac

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-crul >=0.7.0
    - r-data.table >=1.12.0
    - r-digest
    - r-dplyr >=0.5.0
    - r-hoardr >=0.5.2
    - r-jsonlite >=1.6
    - r-ncdf4 >=1.16
    - r-tibble
    - r-xml2 >=1.2.0
  run:
    - r-base
    - r-crul >=0.7.0
    - r-data.table >=1.12.0
    - r-digest
    - r-dplyr >=0.5.0
    - r-hoardr >=0.5.2
    - r-jsonlite >=1.6
    - r-ncdf4 >=1.16
    - r-tibble
    - r-xml2 >=1.2.0

test:
  commands:
    - $R -e "library('rerddap')"           # [not win]
    - "\"%R%\" -e \"library('rerddap')\""  # [win]

about:
  home: https://github.com/ropensci/rerddap
  license: MIT
  summary: 'General purpose R client for ''ERDDAP'' servers. Includes functions to search for
    ''datasets'', get summary information on ''datasets'', and fetch ''datasets'', in
    either ''csv'' or ''netCDF'' format. ''ERDDAP'' information:  <https://upwell.pfeg.noaa.gov/erddap/information.html>.'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: rerddap
# Title: General Purpose Client for 'ERDDAP' Servers
# Description: General purpose R client for 'ERDDAP' servers. Includes functions to search for 'datasets', get summary information on 'datasets', and fetch 'datasets', in either 'csv' or 'netCDF' format. 'ERDDAP' information:  <https://upwell.pfeg.noaa.gov/erddap/information.html>.
# Version: 0.5.0
# License: MIT + file LICENSE
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut","cre"),  email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135")), person("Ben", "Tupper", role = "ctb"), person("Roy", "Mendelssohn", role = "ctb") )
# URL: https://github.com/ropensci/rerddap
# BugReports: https://github.com/ropensci/rerddap/issues
# LazyData: true
# VignetteBuilder: knitr
# Depends: R (>= 2.10)
# Encoding: UTF-8
# Language: en-US
# Imports: utils, crul (>= 0.7.0), dplyr (>= 0.5.0), data.table (>= 1.12.0), jsonlite (>= 1.6), xml2 (>= 1.2.0), digest, ncdf4 (>= 1.16), tibble, hoardr (>= 0.5.2)
# Suggests: roxygen2 (>= 6.1.1), knitr, rmarkdown, testthat, akima, ggplot2, mapdata, plot3D, vcr (>= 0.2.2)
# Enhances: taxize
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-02-01 22:45:07 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>), Ben Tupper [ctb], Roy Mendelssohn [ctb]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-02-01 23:00:04 UTC
