{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rerddap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rerddap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rerddap/rerddap_{{ version }}.tar.gz
  sha256: 1ebbbc317c69d65df8e09fd1d1dc16cda176adc912b9e8e7e5bf7e1cb03fcad6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crul >=0.7.4
    - r-data.table >=1.12.0
    - r-digest
    - r-dplyr >=0.5.0
    - r-hoardr >=0.5.2
    - r-jsonlite >=1.6
    - r-ncdf4 >=1.16
    - r-tibble
    - r-xml2 >=1.2.0
  run:
    - r-base
    - r-crul >=0.7.4
    - r-data.table >=1.12.0
    - r-digest
    - r-dplyr >=0.5.0
    - r-hoardr >=0.5.2
    - r-jsonlite >=1.6
    - r-ncdf4 >=1.16
    - r-tibble
    - r-xml2 >=1.2.0

test:
  commands:
    - $R -e "library('rerddap')"           # [not win]
    - "\"%R%\" -e \"library('rerddap')\""  # [win]

about:
  home: https://github.com/ropensci/rerddap
  license: MIT
  summary: "General purpose R client for 'ERDDAP' servers. Includes functions to search for 'datasets', get summary information on 'datasets', and fetch 'datasets', in either 'csv' or 'netCDF' format. 'ERDDAP' information: <https://upwell.pfeg.noaa.gov/erddap/information.html>."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: rerddap
# Title: General Purpose Client for 'ERDDAP' Servers
# Description: General purpose R client for 'ERDDAP' servers. Includes functions to search for 'datasets', get summary information on 'datasets', and fetch 'datasets', in either 'csv' or 'netCDF' format. 'ERDDAP' information: <https://upwell.pfeg.noaa.gov/erddap/information.html>.
# Version: 0.6.5
# License: MIT + file LICENSE
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut","cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135")), person("Ben", "Tupper", role = "ctb"), person("Roy", "Mendelssohn", role = "ctb") )
# URL: https://github.com/ropensci/rerddap
# BugReports: https://github.com/ropensci/rerddap/issues
# LazyData: true
# VignetteBuilder: knitr
# Depends: R (>= 2.10)
# Encoding: UTF-8
# Language: en-US
# Imports: utils, crul (>= 0.7.4), dplyr (>= 0.5.0), data.table (>= 1.12.0), jsonlite (>= 1.6), xml2 (>= 1.2.0), digest, ncdf4 (>= 1.16), tibble, hoardr (>= 0.5.2)
# Suggests: roxygen2 (>= 6.1.1), knitr, rmarkdown, testthat, akima, ggplot2, mapdata, plot3D, vcr (>= 0.2.6)
# Enhances: taxize
# RoxygenNote: 6.1.1
# X-schema.org-applicationCategory: Climate
# X-schema.org-keywords: earth, science, climate, precipitation, temperature, storm, buoy, NOAA
# X-schema.org-isPartOf: https://ropensci.org
# NeedsCompilation: no
# Packaged: 2019-07-19 22:51:18 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>), Ben Tupper [ctb], Roy Mendelssohn [ctb]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-20 04:30:02 UTC
