travis:
  secure:
    BINSTAR_TOKEN: sViD7NTuWrWpstFOauTnupsVj4QsbLg52mz+OAzIpo9PwNsfZjuN0MEMD+Y0d8LsGAUCr3aC4VvOtRS6dCvoVKUFLugh8IjxqNZ+2hcAEwFRkIdXnRdq856MLL/4Sv/GOyLQain1JQDkuYgR3l4QfXgtogTaEiGiukq5frym9giDdlsZD3PXRbBDs/WqlgPAfdv2IJK1AB8OeDvnfk8o3e25IIhvuwSkByzw4Sc/Vsi67yRN7k3ipE4aHY2weuDWZtbIPCo4is3hzULGbCRoO+1RmypXtY65lCMceliGPfE1qY8Yg3Oq+pG3xYgNTAEKv6EOvaI2M5k0croojzy5eNDHHYYXr7LS3TMfCkl/eKyAvSUNM07YEbe0GtZlV72+V7jnECgALeBo+j+SP1EwnEZlKZknIzSyksHkXSMd1ODmDlWJRN8dwtT3LsGgTHDTJFwIS7DR0JHhPcdwAMPPeEidBYMQbFBNd7ljoOjNKj3qN7NYnxvv388omzjGpMjWR+oWeCSk7HmuKDuJHL5weDmiuMBKGci6UbXjSQPtD68xQtVQfgtRgwqjkDR1op2jPOIm6DY3P5fWSs55brPek+N8YA1c1dOeET9O8yXRWUQeez+qZr7Iu1Rmb1Skl2Uvcd1NFa5j8tYHRxgckysYxowemMKEEKXVj1b5TbYFSKA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
