travis:
  secure:
    BINSTAR_TOKEN: QkBhRY7cR8S+HgCqfA2KhqAKqmfL2NMFn7b4/bPYpQ5qDkiPkj4WjxVeA3XS2F/Y9bpDXCycDOF3CZtUsbiPbKXunJrPZ4gvBCafxUcSBm8hirnSIhydSnx0h2ctH54g3RVVRg5KuNKidXZv7pzkgtPmEI+X+SvR1tOmLYOvm5mYgfDokAXGA/4N7HxFVcjt9HjMkxjvTjHFdIEH5JFmR2Lh8F6g5Vev60AbviJe6NIsGRmsZueuF+hyTqkcVkgx13F5+2Fk9HYcZgDGBDqBW6z3IsTF3UzVHg1QUVY4zyEjfL8u1SaEIqEdxvQMCd0IX0w+AG0cpWY9vSt/Lg7VTIvRM7LmOfqTib6cq9K7FG0aLoYJLiPOYS7yGJJ5gY7ACJX7Fx1F7jSSq4jMJ4xCQmNIM+tujTEiT39ayanMpQlNht7709lQj2F1w413iLPVbUCi8eQ5h8w1edtLeaSleWC45I6uHSNtdfbNzEUnTHLHCZAG8gm4eJUEYqw6TqHmQsvq0yK97WbuMf0tbZBo1nWK25NYHfJge1D0+7kZUOnDKSegBr7MwuOo1pELpI24RwsYYvU8korZXU8fc/En0JYjA46byJBhmQl9/+KPz/8ErJ0BvQ+7N6By4L8OkjhPgFbvUqeqB/N2xnjR4AcdZf+ZPwgM8GYPD+0FK3lmH1w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
