travis:
  secure:
    BINSTAR_TOKEN: ZR/hxLs68GaouPu21AeV5RnybukOf+5udaAnE7SLRbvkYuUiAR7Lh1AGH8HTjIHmpKB0QHoRJozzilDq4BJKDyEUZjlzPUmwxOiYGIQP0UtFLZJgNBSY5782hLbt3GqzgRkj9ppYyi8UPExP2y80k+mxyTSY5AqmFBpfzpeaR27Z6hJyOVJR3OMIaxjn+AhJIm/C5MoxBAKDM15ozzKhLECDls3dR+/WsVHG408Y5wf/gbo+Tw+NCA0crHDTJcgGeNyr+gYMuHeN+Yg+p3oU56RgM/j9E7/AbNXgGK89eNb+dACVCpGFSWqGR8TvPO/UJja03Hlw8NwmwCHKwsPgZlAdf3CBsNc77SBpoXDhljv9lHKovS1flUJMlgDykeGw7wqRPiCiWOryx/X1w+ZtB+u5ny3IHez1pdgoCuP3q7aJVt7w0AlOV6HxoSZzoAzs5p5l/+cMLqeLDZD0P4givezJ7gVlmrYHEvMePqkjsDl1E7FYgpbTHXBux/BEP5O2bzIKPXaQFHrvmK8hXAxB9PTyRxGKxbhbwG3a3HeAx55QNQxlx0yjIWqo2f14yXfDeQzxXJ4hXy+jGMREf/cOePnc9DcVoAq+RqtDO6On3HuhlLgdfxv+BEOHxK6dQrkl9LhA1jzOuvv1VNxiMkJi9CiU3WCoQ6ZANgXwDfrdWCw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
